version: '3'
services:
  mysql:
    image: mysql
    environment:
     - MYSQL_ROOT_PASSWORD=pass
    volumes:
     - sql-data:/var/lib/mysql
  springboot-crude:    
    image: springboot-crude
    ports:
     - 8080:8080
volumes:
 sql-data:
  driver: local
  